### PR TITLE
kconfig: changes on various input files, which are a problem at update

### PR DESCRIPTION
**Pull request by PeterPawn**
A boolean value uses the keyword 'bool' instead of 'boolean', a 'help'
keyword without any text produces a warning message and DOS line-ends
(\r\n) are an 'invalid character' at the position of '\r'.

See https://www.kernel.org/doc/Documentation/kbuild/kconfig-language.txt
for a syntax description.

### CODE REVIEW

**Comment by PeterPawn** [comment]
Oops ... it was only a draft yet. :smiley:

I'll close it now ... thanks for merging. But future PRs may contain incomplete work (that wasn't the case here) at the first stage - please keep this in mind.

**Comment by er13** [comment]
I "reviewed" the commit and found it plausible and complete, so why wait.

What are your next steps? Do you plan to update the kconfig version?

**Comment by PeterPawn** [comment]
Yes ... I'm working on a proposal for the version from the current kernel sources and during these work I had found the now-changed problems.

There are some additional patches needed ... the new version has a different dependencies handling and I'm trying to find a solution for the [340-something patch](https://github.com/Freetz/freetz/blob/master/tools/make/kconfig/patches/340-do_not_select_unmet_direct_dependencies.patch) - other parts are working already (but the patches have still offsets and need a refresh).

Another problem is the availability of a (secure and public) source for the code, that supports partial downloads via `git-archive`. Looks like my proposal needs either a 'hand-crafted' source archive or it has to contain the source files itself - I had cloned the kernel git repo to my local server (with `--mirror`) and extracted the files from it with `git-archive`. 

But that's the problem to be solved next ... first and now the proper patches are needed. Nevertheless I would like to know, whether an 'embedded source sub-directory' or an external archive file are prefered at the end - both approaches are used now under `tools/make`.

**Comment by er13** [comment]
As far as I remember only a couple of repositories support git_archive method. [repo.or.cz](https://repo.or.cz/?a=project_list;t=kernel) is (was?) one of them. [kernel.org](https://git.kernel.org/) used to support it but dropped the support some time ago. This is the reason kconfig sources are downloaded from [repo.or.cz](https://repo.or.cz/?a=project_list;t=kernel).

kconfig package currently uses [linux-2.6](https://repo.or.cz/linux-2.6.git) repository which is not updated since years. But [repo.or.cz](https://repo.or.cz/?a=project_list;t=kernel) contains another repository [linux-2.6-linus](https://repo.or.cz/linux-2.6-linus.git) which gets synced and contains Linus' master and all the recent releases.

Could you please test if git_archive method still works with [repo.or.cz](https://repo.or.cz/?a=project_list;t=kernel) and the needed files could be downloaded from [linux-2.6-linus](https://repo.or.cz/linux-2.6-linus.git). Thanks!

**Comment by er13** [comment]
With the following change I'm able to download the latest kconfig version (`v5.1-rc2` as of now) using `git_archive` method.

```diff
--- a/tools/make/kconfig/kconfig.mk
+++ b/tools/make/kconfig/kconfig.mk
@@ -1,6 +1,6 @@
-KCONFIG_VERSION:=v3.11-rc3
+KCONFIG_VERSION:=v5.1-rc2
 KCONFIG_SOURCE:=kconfig-$(KCONFIG_VERSION).tar.xz
-KCONFIG_SITE:=git_archive@git://repo.or.cz/linux-2.6.git,scripts/basic,scripts/kconfig,scripts/Kbuild.include,scripts/Makefile.build,scripts/Makefile.host,scripts/Makefile.lib
+KCONFIG_SITE:=git_archive@git://repo.or.cz/linux-2.6-linus.git,scripts/basic,scripts/kconfig,scripts/Kbuild.include,scripts/Makefile.build,scripts/Makefile.host,scripts/Makefile.lib
 KCONFIG_DIR:=$(TOOLS_SOURCE_DIR)/kconfig-$(KCONFIG_VERSION)
 KCONFIG_MAKE_DIR:=$(TOOLS_DIR)/make/kconfig
 KCONFIG_TARGET_DIR:=$(TOOLS_DIR)/config
```
```
$ make kconfig-source
tools/freetz_download dl kconfig-v5.1-rc2.tar.xz git_archive@git://repo.or.cz/linux-2.6-linus.git,scripts/basic,scripts/kconfig,scripts/Kbuild.include,scripts/Makefile.build,scripts/Makefile.host,scripts/Makefile.lib

--2019-03-27 21:50:24--  http://freetz.magenbrot.net/kconfig-v5.1-rc2.tar.xz
Resolving freetz.magenbrot.net (freetz.magenbrot.net)... 31.172.113.113
Connecting to freetz.magenbrot.net (freetz.magenbrot.net)|31.172.113.113|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-03-27 21:50:24 ERROR 404: Not Found.

Download failed - "http://freetz.magenbrot.net/kconfig-v5.1-rc2.tar.xz"  ->  error code 8

--2019-03-27 21:50:24--  http://freetz.wirsind.info/kconfig-v5.1-rc2.tar.xz
Resolving freetz.wirsind.info (freetz.wirsind.info)... 188.165.115.52
Connecting to freetz.wirsind.info (freetz.wirsind.info)|188.165.115.52|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-03-27 21:50:24 ERROR 404: Not Found.

Download failed - "http://freetz.wirsind.info/kconfig-v5.1-rc2.tar.xz"  ->  error code 8

--2019-03-27 21:50:24--  http://freetz.3dfxatwork.de/kconfig-v5.1-rc2.tar.xz
Resolving freetz.3dfxatwork.de (freetz.3dfxatwork.de)... 31.172.113.113
Connecting to freetz.3dfxatwork.de (freetz.3dfxatwork.de)|31.172.113.113|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-03-27 21:50:24 ERROR 404: Not Found.

Download failed - "http://freetz.3dfxatwork.de/kconfig-v5.1-rc2.tar.xz"  ->  error code 8

Checking out files from the git_archive repository...
Packing checkout...
```

Let me know if the list of the files needed is still valid. If so, I'll upload the tarball to the Freetz download mirrors.

And thanks for your effort to update the kconfig version.

**Pull request closed without merging**
