### PR TITLE
mc: make install location selectable

### PR DESCRIPTION
**Pull request by PeterPawn**
- these additions make it possible to run 'Midnight Commander' from a (CONFIG_PLUGINV2-compatible) plugin-image, if it was built with appropriate pathnames

### CODE REVIEW

**Comment by kriegaex** [comment]
Quoting myself from #14: What has a different location on the file system? Please do not use commit comments requiring me to read the full diff in order to know what you did when I just want to use "git log".

**Comment by PeterPawn** [comment]
Two points from my side ... I'm not annoyed, if your comment has a gist or groundwork and there is really a reason for criticism.

But if I get the impression, that you've commented something without reading the other messages and as a result, you may see and judge only one half of a story, then I am (comprehensible or not) "pissed off".

That's the second "incident" in contacts with you, where I got such an impression ... the first was your opinion in a Trac ticket, where you've vanished immediately after your disapproval without any further reaction or explanation and the second is your first comment on #12.

As far as I can see, I did exactly that, what you've suggested there ... and I did it prior to your comment - so I would bet, you did not read any other message, before you wrote this comment. If I am wrong here, I do not understand the whole comment.

I have no problem with a "SCM police" ... but I expect fairness, courtesy and correctness and - due to your later editing of your first reaction - I would think, you realized yourself, that you've overstepped the mark something.

In another place you've judged my behavior as "oberlehrerhaft" ... even if I can follow your comments here in some points, I would think, such a "massive" criticism isn't reasonable or fitting here - as long as there are no coordinated guidelines. 

So far it's only one more opinion and even if you refer yourself to your (global) experiences with SCMs ... my own experiences with suggested patches/changes for the Freetz project have shown, that no patch (not even one, as far as I remember) was incorporated "as is".

Now you could think (or say), they were really insufficient and each of these "corrections" was needed ... if this would be the case, I should consider to give up programming at all.

You blame me some weeks ago, my reactions (in the Trac ticket) would scare off Freetz users from further collaboration ... what do you think, how "motivated" I still am, if the first step in a new direction (without any template as a "boiler-plate" or other "ready to borrow" experiences - for this project, to avoid misunderstandings) is denigrated in this manner.

**Comment by kriegaex** [comment]
Peter,

this is not the place to even old bills. Please let us stay in the context of this PR here. If you like to discuss what you think is a personal problem between us, I am glad to have an audio or video call with you, chat with you or, if all else fails, write e-mails. But e-mails tend to develop into flame wars and those are tedious. Even the discussion here is kind of tiresome. Where I mean to provide feedback and ideas for improvement, you see attacks. There are none, rest assured.

My point is: Just **because** I am an inactive developer lacking context, I am the perfect test case for your PR comments, commit messages etc. because if I do not understand them or find them ambiguous, others might, too. If I can understand them, active devs will probably, too.

**Comment by PeterPawn** [comment]
> what you think is a personal problem between us

It isn't ... it's a question of "correctness".

If someone enters a discussion, throws a 'firebomb' and vanishes without any further check, what the result of his intervention is, that's at least negligent and if the same person appears on another platform again like a 'genie' (I don't mean 'genius' here), **it is doubtful** ... as long as he wasn't able to further keep part in the other discussion.

These statements afterwards:

> this isn't the right place, let us discuss this in a more private manner

are (strange, isn't it?) never valid **for their first claims**.

And if anyone starts such a discussion in the public (and your comment in Trac *was offending* - that's not the question), it has to be concluded in the public too. There's no reason to become shy suddenly and to continue a dispute with more 'privacy' (if both parties are adult).

So you have to live with my doubts ... I didn't suck them from my fingers, they're the outcome of your earlier reactions and false claims - at least is that my opinion and you should have read this already elsewhere.

And to avoid any further misunderstandings ... I do not criticize your Trac comment and your opinion per se - it is your later (and ongoing) behavior, which bothers me there (and meanwhile here too).

**Comment by kriegaex** [comment]
I am sorry and apologise for all the trouble I have caused you with my sudden appearance on Trac and here. I appeared there because I found your way of communicating with a ticket author rude. I alpeared here because I wanted to support your GitHub usage and at the same time help you improve your way of using Git. That's all.

You cannot seem to handle feedback, so I am out of here, not wasting my time with you any further.

P.S.: Have you ever noticed that I did not review or criticise a single line of code? I wanted to leave that to an active developer. I wanted to stay on this meta level where I still felt I could contribute some added value to the project.

**Comment by PeterPawn** [comment]
Alexander ... honestly: I don't think, that you're mentally not able to see my point. 

Your appearance in the [Trac ticket](http://freetz.org/ticket/2921) showed a view on this dispute from a "key hole perspective" and my criticism (and the basis for my decision, to pull myself out of Trac again) is  not your point of view or your disapproval at all. 

I find it just cowardly and incomprehensible, if there's no further answer on my request, to explain the accusations better and - if possible - provide any proof (e.g. a cite (with link) of a rude comment by me, where I wasn't earlier provocated). 

Your own intention (expressed later here on GitHub) to talk about this only in private anymore, can't be in my interest. A public accusation (and you had other opportunities at the time, where you wrote your offending Trac comment) needs a public conclusion as finale, all other attempts are at least dishonest, sometimes even hypocritical.

My argument, that I had defended myself only against rude reactions from the other party (and you may still review the whole dispute on Trac, I've never edited the content or changed statements later, the only edited parts are corrected typos - there's a history on Trac to verify this), never got noticed by you ... or you thought, you're not obliged to further answers (no matter, if your accusation was substained or not). 

Your further accusation as a "bonus", I would do this for a long time and repeatly, was also never proofed (I had written, why this is impossible). And last but not least ... as a cream, you write down all this as your "expectation", what I did just in this (Trac) discussion earlier - sorry, **THIS is a proof** for the assumption, that you never had read the comments in front of it.

That's the manner, how such projects really get destroyed ... and if your allegations were really justifiable, it should have been easy enough to explain them and write this down somehow.

But the lack of any reaction to the following comments from my opponent in this dispute implies, that you obviously share his point of view in each other disputed question, no matter how abstruse it became (and here I would like to reference especially to his last comments).

As a result, I had to leave the Trac site again, to avoid further disputes with a man, who is - obviously - not willing to communicate in a reasonable manner (and a "monolog" isn't reasonable discussion). This was written by me explicitly - there could be no doubt about my motives for leaving.

Afterwards I've switched back to another platform ... and suddenly re-appears the same person with another comment, which was also "offending" in its first version or - better expressed - shows exactly the same "key hole view", which was the reason for the first clash. 

( And even if this first version isn't visible anymore in #12 now (and I can't find a history for comments here), I've got the notification e-mail with your first version and I've stored it here, if you want to read it yourself again. )

Doesn't show this sudden re-appearance (now even on GitHub) with a next "lecture" something like an "obsession"? Especially, if this comment is - more or less - without a relation to the PR itself and only points to another (and in my opinion) unambigious comment - at least, if somebody really reads, what was written earlier?

[BTW ... I hope, you're not also the owner of domains related to GitHub, as you has made clear for freetz.org on Trac - and no one had ask for it.]

If someone knows, that a "relation" is already under strain, I'd expect further steps more "on toe tips" (and it doesn't matter, whether the nails are cruelly curled or not) and a statement:

you're my "victim" 

(your wording, not mine) is unsuitable in such a context ... even if it was "escaped" here with quotation marks. 

And it's not impossible for someone, to feel really as your victim - to be more precise: as the "victim" of another premature (and not very well thought out) statement. 

This lets me view on each of your further ideas with strong prejudice and you can't be really astonished about it. Please keep in mind, I mean solely your comment in #12 here as the basis of my reluctance, the later ones are less "impressive" (and less aggressive).

Would you now - in my position and with our history in mind - trust on a statement, that a criticism (#12) was only meant to be "constructive"?

Your only conclusion was, I'm not able to work in a team. How would you assess your own behavior, if you look over the whole situation?

Is it really impossible to contribute further to the Freetz project, without running into a dispute with you again?

Even your later declaration, why you wrote your first comment (and here I refer to its "first edition"), is somewhat lame. Why?

You wrote, you were not able to see, what I meant with a "branch" and I had better written "user story" or "feature" to explain it further.

If you read my comment on the first PR, I wrote there:

> Soon I will generate more pull requests ...

At the time of your comment, there were four other PRs (and they were there for hours and not only for minutes). It should have been easy enough, to take a glance onto them too, before you wrote your comment. 

Furthermore ... as an expert for Git/GitHub you should know, how to use the "network graph" to find the commit, where a branch was started. A first glance here should had shown you too, what my idea of a "branch" was.

Your (even later and with more politeness added) explanation, how anybody should use GitHub in your opinion, was therefore also unnecessary (thanks for your salute, maybe I'm using GitHub really in a manner, which would make you lucky) ... and if you really would read, what the other party wrote and you would thoroughly check your facts and this also **before** you write an own comment (as others may expect it), some clashes would - presumably - never occur.

And so it's my own conclusion, that your contribution wan't really a "constructive criticism" - it was more a "premature ejaculation" (of words from the very first thought and view).

And this first comment leads to a situation, where your further (and possibly helpful) statements are read also with prejudice ... nobody can get out of his skin, that's my excuse. And where did you prove earlier, that your able to switch from some superflous statements to helpful comments - from one second to the other?

Your final statement, you will not waste your time anymore with a further dispute, isn't very useful too ... wouldn't it better to "shine" instead with substantiated arguments, which are not so easy to expose?

---

Sorry for this "extra large" text ... due to your announcement, that you will not answer anymore, I had to use this last chance, to clarify and explain it from my point of view.

**Comment by PeterPawn** [comment]
das ganze bild
Maybe, this picture best shows my own accusations to you.

**Comment by er13** [comment]
https://github.com/Freetz/freetz/pull/15/commits/062c4a20e5da95ea8246f85591ec6196b41399b7 is incomplete:
 - mc.mk still contains some **usr**, **usr/share** references
 - external related changes are missing

Besides that I consider this change to be very YourFritz specific. It is absolutely of no use for Freetz.

Please keep maintaining it in your fork.

**Comment by PeterPawn** [comment]
No problem, ... I'll keep it in my fork.

But could you please give me a hint, where the mentioned additional references may be found?

External processing was indeed ignored, because the changes were intended to separate the package from the "usual install location" and in my opinion they're mutually exclusive with "plain externalization" - maybe I should enforce this with appropriate dependencies. 

---

I'll try later to prepare an example with 'mc', how a 'self-contained image' with 'ncurses' and this package would look like ... and how it may be made with the Freetz toolchain already nowadays. 

At the moment there is a step-by-step list to follow, to get an autonomous package:
- set the appropriate path names in .config
- run 'make ncurses-precompiled'
- run 'make mc-precompiled'
- copy the files from 'packages/somewhere' to a separate directory (a specialized 'install-something' target in the Makefile would be much better here)
- create a SquashFS-Image from them
- create and sign a TAR archive with a './var/install' script and the just-built SquashFS image

It should be possible to automate these steps (each of them is already used somewhere in the toolchain) and to invent new build targets like 'mc-image' or 'openvpn-image' for such encapsulated firmware extensions, which may be added dynamically using the (already present) plugin mechanism from AVM. 

If you need only a small amount of additional software (I would say, up to 4 or 5 packages), it should be possible to maintain a separate image for each of them. If this number grows, it's better to integrate packages a little bit more and use a 'base image' for often needed extensions.

With appropriate scripts to control mounting and dismounting of such a package (incl. start/stop for services started from there), it's also possible to replace a package "on the fly" with a newer (fixed) version, without any need for a reboot or to flash a new image. I would really think, that some Freetz users would appreciate a solution, where some frequently changed/updated packages may be replaced without the need to create a complete new image or even to reboot the device.

The (mostly) missing PLUGINV2 scripts from AVM aren't really needed, the core component is here 'tr069fwupdate packet' with its abilities to check a signature, unpack the image and call the embedded 'install' script. 

You need only a generic 'starter' script, which initiates this process somewhere ... maybe from an upload form, where the package was sent from user ... or from another page, where an URL to download such a package was given ... or due to any other trigger and with a file from any other source (up to an USB volume).

Security (as needed here and it's (really) important) is still guaranteed by the requirement, that such an extension has to be signed with a known and valid key.

For packages, which need writable persistent settings, a generic "on demand" definition and save/restore mechanism (from Freetz) would be use- and helpful ... but some settings (e.g. an 'authorized_keys' file for a SSH server) may be maintained in the extension image too.

But all of these opportunities are only a serious option, if it's possible to configure a package in any way, that it uses other path names than '/usr' (as --prefix for most autoconf invocations) - at least, if such a package uses static path names in its code. This aren't so many of them ... but 'mc' is one of the biggest problems, because it searches its various helper files only in fixed locations. 

Most packages need only a customized path, where they have to look for their settings (and with Freetz this could still be "/tmp/flash/anything", 'cause it's writable by './var/install' script from an image). This package here (as the hardest task - in my opinion) was intended as a first food for thought, how a package could be made 'relocatable'. Why this could be useful (still only in my own opinion), should be clear (explained) now.

**Comment by er13** [comment]
Ok, I understand the use-case after your explanation but the proposed change is just miles away from it, it's just a very, very small step (less than 1%) towards it.

Instead of implementing it for each package I would suggest to make **prefix** configurable for all packages at the same time, just like [FREETZ_RPATH](https://github.com/Freetz/freetz/blob/8cd7c82a33685094e4e5f1eb9fe3feef478f54b5/config/ui/toolchain.in#L310).

That is, introduce a variable for "package install prefix" and adjust all (up to now) [hardcoded references to **/usr**](https://github.com/Freetz/freetz/blob/39664df58c6034a9e64e8df9871d9ea22b7d19da/make/Makefile.in#L149).

This way the feature would be available for all packages, this way additional non-freetz menuconfig entries won't bother a freetz user.

@ still existing references to **usr** in mc.mk: [1](https://github.com/Freetz/freetz/blob/062c4a20e5da95ea8246f85591ec6196b41399b7/make/mc/mc.mk#L73), [2](https://github.com/Freetz/freetz/blob/062c4a20e5da95ea8246f85591ec6196b41399b7/make/mc/mc.mk#L98). You probably had only YourFritz in mind while implementing 062c4a20e5da95ea8246f85591ec6196b41399b7. If a freetz user would change the options added in it, nothing would work.

**Pull request closed without merging**
