### PR TITLE
6490 alpha Stand

### PR DESCRIPTION
**Pull request by f-666**
Der Kode von diesem Pull Request kompiliert und läuft auf einer 6490.

Ich würde sagen, er hat alpha Status:
Bisher wurde nicht viel getestet und es wurde noch nicht versucht, alle Pakete zu bauen.

Für weitere Tests (und wahrscheinlich Fixes) sollte das hier aber eine gute Grundlage sein.

### CODE REVIEW

**Comment by er13** [comment]
Almost everything has been merged except for the following parts (I hope the list is complete)

- FREETZ_AVM_SOURCE_6490_07_00 related parts of https://github.com/f-666/freetz/commit/1c5e8041a77f88d0ffea427c3e165eb2cd79946f
  the corresponding AVM opensrc package is not yet available (at least to me)
- download toolchain related commit https://github.com/f-666/freetz/commit/5e0b064b4d41a028e9775690bf247fb652821a0e

**Comment by er13** [comment]
@f-666:

Have you had the time to check if I missed something while merging?

The parts intentionally left out are listed in https://github.com/Freetz/freetz/pull/22#issuecomment-431710658.

**Comment by f-666** [comment]
Sorry, I don't have time this week. Next week I will check and rebase.
I guess all links in the freetz trac will be invalid afterwards?

**Comment by er13** [comment]
Ok, thanks!

If you rebase all your commits (and thus also links) will most likely get lost. Just keep the branch as is without rebasing, i.e. let it "die". Start a new one if some parts are missing or wrong.

**Comment by f-666** [comment]
OK, closing this pull request.
Open points as mentioned:
-7.00 for 6490
-download toolchain for i686

**Comment by f-666** [comment]
root@fritz:/var/tmp# ./bash_cv_must_reinstall_sighandlers && echo 'no' || echo 'yes'
no

**Pull request closed without merging**
