### PR TITLE
Change of push_firmware

### PR DESCRIPTION
**Pull request by sanswitcher**
Found a nasty bug in the push_firmware script:

the ncftp-calls were wrong so that the update of the firmware fails.

The script was tested with a FB7581 that uses flashing ram-boot.

I've changed the location of the "-C" parameter to " -C  "${ip} " and removed the "-Y "quote QUIT \"  command line.

After these changes the update with ncftp selected via "-cmd ncftp" worked fine.

"[push_firmware_eh.zip](https://github.com/Freetz/freetz/files/9940983/push_firmware_eh.zip)

### CODE REVIEW

**Comment by f-666** [comment]
wrong project

**Comment by sanswitcher** [comment]
Howto send my modif to freetz-ng???

**Comment by PeterPawn** [comment]
https://github.com/Freetz-NG/freetz-ng

- clone the repository
- check, whether changes are really needed (`push_firmware` was heavily changed in Freetz-NG already)
- apply your changes, rebase to `master` branch from repository above
- create a new pull request in the Freetz-NG repository

**Comment by JokerGermany** [comment]
> Howto send my modif to freetz-ng???

you don't want to.
freetz-ng isn't near stable as the developer version of freetz was...

**Comment by vaxinf** [comment]
This patch only applies to freetz-ng.

**Pull request closed without merging**
