### PR TITLE
openssl: add optional support for a static binary

### PR DESCRIPTION
**Pull request by PeterPawn**
A statically linked binary is easier to handle (when it's loaded into an already running FRITZ!OS system), if it does not depend on further libraries.

### CODE REVIEW

**Comment by kriegaex** [comment]
Because I like GitHub, you are my first "victim", Peter. The same comment could apply to other devs:

Please provide commits with meaningful messages, especially meaningful headlines (but not too long). For instance, write "OpenSSL: add support for static binary"

**Comment by PeterPawn** [comment]
This pull request was made from a branch named "openssl" ... I would think, that's  enough as "hint". 

The maintainer can/may/would change the headline and the whole message at any time and this will be done anyway, as my experience teaches - not only because it's inaccurate, solely from principle. 

If this was really 'only a comment' (the previous one from the earlier pull request lets me doubt here)  ... it's no problem to add the name of the affected package to the headline and I've changed it for the pull request.

But instead of such a single comment (in a pull request, which will be closed one day and never read again by other contributors) it's obviously better to publish any guidelines ... finally it will save time, if there's no need to repeat yourself anymore.

**Comment by kriegaex** [comment]
Hello again, Peter.

I cannot keep you from doubting my statements, but I kindly request you to believe that I say what I mean and mean what I say.

The problem with your commit messages is that they only make sense or can be fully understood when read in the context of your feature branch name. But after a merge onto master or any other branch nobody can see the name of your previous feature branch anymore, so this is not good practice. Please write commit comments which carry enough context to be understood by themselves. Ideally, my grandma should understand them. (You know how I mean it.) Do not assume that every other developer or contributor reads them in the same context as yours when you wrote it. You do not mainly comment for yourself, but for others. Remember, on master all you have is a linear history (git log). In most cases, when using a feature branch model, feature branches even get deleted after merging. Maybe the old branch heads get tagged if such a convention exists (in my coachee teams it does), but that is optional. Either way, the information is invisible when reading the log.

**Comment by PeterPawn** [comment]
Once more ... I can see your point with an inaccurate commit message and I share your POV there - as a result, I've changed the headlines, the explanations were detailed enough in my opinion.

But if you really (had) read my whole comment from the first and second attempt (incl. the statement, this text should be taken as addendum to all following PRs from this "run"), you should have recognized, that I'm not expecting, only one single word from my "explanations" (incl. the headline) in this PR will ever reach the SVN trunk:

> In any way it should be possible, **to patch the SVN trunk with the 'diff' file** from this request.

So you'll never read my words in a 'git log' output ... or the workflow has to change immediately and that is - at least - unlikely.

**Comment by kriegaex** [comment]
I have never said or meant what you understood. And I still cannot stop you from believing that I did not read carefully each single word you wrote. I do know what the long and helpful comment in the other PR was meant for.

But did you get my point? I never suggested you to change the topic of this PR because, as you correctly said, it will never appear in any Git log. I suggested to change the **commit message** which does appear in the log. So please edit your commits, not just the PR.

As I said in the other PR, there will be no further feedback from me here.

**Pull request closed without merging**
