### PR TITLE
 bind: version bump to 9.11.6-P1 and fixes

### PR DESCRIPTION
**Pull request by cawidtu**
* bump version to 9.11.6-P1
* included patch from https://gitlab.isc.org/isc-projects/bind9/commit/ef49780d30d3ddc5735cfc32561b678a634fa72f
  to fix compilation problem with uClibc
* fixed bug in rc.bind (stop() called by modlib_stop(), resulting in doubly attempted kill for 'named' process)
* removed obsolete stuff from bind.mk

### CODE REVIEW

**Comment by er13** [comment]
Please explain the changes made to rc.bind. Why did it happen twice? What about `restart`?

**Comment by cawidtu** [comment]
The function modlib_stop() from `etc/init.d/modlibrc`, which called in rc.bind, looks as follows:

<CODE>
modlib_stop() {

        local fn=$PID_FILE

        local id=$(cat "$fn" 2>/dev/null)

        echo -n "Stopping ${DAEMON_LONG_NAME} ... "

        modlib_check_running

        case $? in

                0)

                        stop_pre

                        stop 0

                        local retval=$?

                        stop_post $retval

                        if ! kill -0 $id 2>/dev/null && [ "$retval" -eq 0 ]; then

                                rm -f "$fn"

                                echo 'done.'

                        else

                                echo 'failed.'

                                return $retva

                        fi

</CODE>

Hence, `modlib_stop()` calls `stop()`, which is defined as a default in `modlibrc` but can be overriden in the `rc.X` file as it is the case here. The present implementation of `stop()` in `rc.bind` kills the process 'named' according to the id found in the PID file. After the call to `stop()`, `modlib_stop()` proceeds with a kill command which then must fail. I noticed this since `rc.bind stop` always returned "failed" although the process has been terminated correctly.

My suggested solution is to use the default implementation of `modlib_stop()` wrapped in a stop/start of multid if applicable. According to my tests, bind is correctly shut down with this solution and `rc.bind stop` returns success. I have no issues with `rc.bind restart` either since this just results in a `modlib_stop` followed by a `modlib_start`.

**Comment by er13** [comment]
> After the call to `stop()`, `modlib_stop()` proceeds with a kill command which then must fail.

I assume the `kill` you mean in the quoted sentence is

```
if ! kill -0 $id 2>/dev/null && [ "$retval" -eq 0 ]; then
```

Please note `-0` after `kill`. It's not the kill, it's a check if the process is still running, s. `man 2 kill`:

```
If sig is 0, then no signal is sent, but error checking is still performed; this can be used to check for the existence of a process ID or process group ID.
```

> I noticed this since rc.bind stop always returned "failed" although the process has been terminated correctly.

So it looks like the process terminates properly but it just needs some time. Please try adding a simple `sleep X` to the current implementation of `stop` and test if it helps.

**Comment by cawidtu** [comment]
Thank you for the clarification. You are right. After adding a `sleep 1` to the stop() method the error disappeared (tested multiple times).

**Pull request merged**
