### PR TITLE
improve isc-dhcp package; add https support for lynx

### PR DESCRIPTION
**Pull request by farebers**
improvements:

- isc-dhcp: cgi now available
- isc-dhcp: allow running the daemon as non-root user
- lynx: add https support

issues:

- isc-dhcp: start before multid doesn't work
- isc-dhcp: stop in rc.<daemon> is implemented without modlibrc (it reported fail for no reason)
- isc-dhcp: not handling possible conflict with dnsmasq's dhcp server

tested on 7490 trunk

### CODE REVIEW

**Comment by farebers** [comment]
das sehe ich ein - kann man einen commit aus dem PR entfernen? habe es nicht gefunden

**Comment by JBBgameich** [comment]
`git reset --soft HEAD~1` löscht den neusten commit aus deinem branch. Mit `git push -f` kann er dann auch auf dem server gelöscht werden.

**Comment by er13** [comment]
@farebers:
I adjusted your code a bit before committing. In particular
 - I moved `cmdline` options from the `.cfg` file to the `rc-script`, options like `-cf`/`-pf`/`-lf` should be controlled by the start-up script and not by the end user.
 - I removed the "`killall $DAEMON_BIN`"-code (your stop-replacement-code). Please investigate the reasons for `modlib_stop` not working once again and provide more information on what's going on so that we can solve it together. I.e. if isc-dhcp is able to access the pid-file (permission problem?), does it write the correct pid to it, does it properly react to `SIGKILL` (btw. `modlib_stop` uses `SIGKILL`, so that I don't understand your comments about `-9` (=`SIGKILL`)). Is is just a timing issue, i.e. we should give isc-dhcpd some time to terminate and only only after that check if it's still running. If so use `stop_post `for that. 
 - Please implement missing features (multid, wrapper).
 - Please don't forget the translations (I had to (re-)add them manually).
 - Please check if I broke something that worked before, I didn't test the committed code on the box.

**Comment by er13** [comment]
Ping

**Comment by er13** [comment]
Closing, no feedback since months.

**Pull request closed without merging**
