### PR TITLE
Cacerts

### PR DESCRIPTION
**Pull request by flosch-dev**
CACERTS will download ca-bundle file and place in /etc/ssl/certs/cacert.pem.
CA-Bundle is required for applications using TLS server auth like curl, stubby (getdns), ...
Further if CACERTS is selected in menuconfig, curl will be configured with "--with-ca-bundle" and set to apropriate location.
This is first version of package intended to bring updated ca-bundle into freetz image. 
I will be happy with any feedback especially about filesystem location.
In future box should update ca-bundle periodically itself, but an initial ca-bundle will always be required to start.

### CODE REVIEW

**Comment by PeterPawn** [comment]
Is it really a good idea, to download a bundle of CA certificates **without any** integrity protection measures?

**Comment by flosch-dev** [comment]
download during build uses also https which provides integrety protection. Do you mean if we should trust the source of ca-bundle or the way ca-bundle get's in the image?

**Comment by PeterPawn** [comment]
> download during build uses also https which provides integrety protection. 

No, it doesn't. Sorry, that's simply the truth.

https://github.com/Freetz/freetz/blob/master/tools/freetz_download#L55

First rule while using "foreign" tools: Ensure it's really doing, what you've expected. If there're no docs, look into the sources.

Sure, other packages use this tool, too. But they provide a hash value to check the result of a download.

**Comment by flosch-dev** [comment]
Agree your concerns, thanks for pointing to right place. I was not aware package download ignores certificates.
Now I see 2 options to address integrity protection which I fully aggree needs to be in place:

1. creating helper function in "include/make/020-helper-functions.mk" which downloads via https with trust chain/server auth.
2. applying hashing (MD5 or SHA256) into package. I don't really like this approach as unflexible when ca-bundle get's updated. 

Would any of those option acceptable? Maybe other option I could consider?

**Comment by er13** [comment]
Please use versioned-links - those containing the date, e.g. https://curl.haxx.se/ca/cacert-2019-05-15.pem and SHA*-hashes.

**Comment by flosch-dev** [comment]
Yes, I will refer to links with dates and add sha256 hashes, looking at the history of changes at curl.haxx.se, the effort to maintain this packages should still be very low.

**Comment by flosch-dev** [comment]
packages was updated, please review and share comments.
Are you fine with target file-system location "/etc/ssl/certs/cacert.pem"?

**Comment by er13** [comment]
Could you please squash your changes, it's hard to review them otherwise.

**Comment by flosch-dev** [comment]
Tut mir echt leid, aber ich bin mir nicht sicher wie ich die ganzen changes jetzt noch squashen kann.
Ich habe in meinem fork ein neuen branch angelegt "cacert-merged" aber dieser pull request ist ja mit meinem branch "cacerts" verknüpft. Kann ich die changes überhaupt noch jetzt zusammen fassen?
Eine weitere Frage... wäre es besser für einen pull requests einen branch mit nur 1 commit zu erstellen?

**Comment by PeterPawn** [comment]
Lokal läßt sich mit einem "git rebase -i <commit>" alles ab dem spezifizierten Commit umsortieren und auch zusammenfassen ... unter Linux (bei Windows weiß ich es nicht) stehen die möglichen Operationen in der "Steuerdatei", die bei diesem Kommando im Editor geöffnet wird.

**Comment by flosch-dev** [comment]
Danke für den Hinweis, ich glaube das hat geklappt.

**Comment by flosch-dev** [comment]
Oh mist, jetzt ist das mit dem commits noch schlimmer geworden, tut mir leid. Eigentlich sind das nur 2 Änderungen, 1. das package cacerts und 2. curl.mk mit "--with-ca-bundle=/etc/ssl/certs/cacert.pem".
Falls das mit dem ganzen commits jetzt zu viel durcheinander ist, kann ich diesen PR auch schließen und einen neuen PR mit sauberen branch anlegen?

**Pull request closed without merging**
