### PR TITLE
yf_patchkernel: new Kconfig symbol for supported models and copyright notice for C source file

### PR DESCRIPTION
**Pull request by PeterPawn**
some minor changes/corrections for [yf_patchkernel](https://github.com/PeterPawn/YourFritz/tree/master/patch_kernel)

### CODE REVIEW

**Comment by er13** [comment]
> https://github.com/Freetz/freetz/pull/148/commits/22b2e1ef11ded24ad8d9ffbf7129c03da9f6ffde

There are a couple of boxes more to test:
 * GRX5: 6890
 * VR9: 3490, 5491 (not yet supported but there is a [PR](https://github.com/Freetz/freetz/pull/145) for it)

Could you please check if your patch would work with these boxes?

**Comment by PeterPawn** [comment]
> Could you please check if your patch would work with these boxes?

Not really ... and I don't think, it's necessary.

Reasons: 

- as mentioned in another place (possibly the previous PR regarding this module), my own opinion is clearly: The module doesn't harm the system, even if it gets loaded while not needed.

- I personally don't own any of these devices

As long as the module is built and therefore available with GRX5 and VR9 devices, it doesn't matter when someone tries to load it, even if it's not necessary (or successful) due to missing BUG_ON statements in the AVM sources.

I'm currently only aware of these two processors, where AVM has inserted the superfluous (or erroneous in context of a TUN/TAP device) BUG_ON statements. 

If other MIPS models get known as problematic, the patch code has to be reviewed anyway, because different instruction-sets may result in emitting different code by `gcc` at the places to patch.

Other platforms (x86/x64 or ARM) need a different solution (or at least an own implementation) anyway.

**Comment by er13** [comment]
I thought this could be checked by taking a look into the corresponding kernel sources.

**Comment by PeterPawn** [comment]
Usually I don't mirror all open-source packages published by AVM - only for the devices, I own or manage myself.

Surely it's possible to look into the source packages for all of these devices ... but are you really convinced, it's necessary? "Probing" is a approved solution in my own opinion and the current proposal keeps the conditions for `AVM_HAS_BUGON_IN_NET_CORE` small and simple.

**Comment by er13** [comment]
> "Probing" is a approved solution in my own opinion
OK, fine with me

**Comment by PeterPawn** [comment]
Meanwhile I've mirrored the whole `osp.avm.de` locally ... here are the models with an already published source package for a FRITZ!OS 7 firmware:

```
vidar:~/osp.avm.de $ find . -name "*07.0[0-9]*" | sort
./fritzbox/fritzbox-4020/source-files-FRITZ.Box_4020-07.01.tar.gz
./fritzbox/fritzbox-4040/source-files-FRITZ.Box_4040-07.01.tar.gz
./fritzbox/fritzbox-5490/source-files-FRITZ.Box_5490-07.01.tar.gz
./fritzbox/fritzbox-5491/source-files-FRITZ.Box_5491-07.01.tar.gz
./fritzbox/fritzbox-6490-cable/source-files-FRITZ.Box_6490_Cable-07.01.tar.gz
./fritzbox/fritzbox-6490-cable/source-files-FRITZ.Box_6490_Cable-07.02.tar.gz
./fritzbox/fritzbox-6490-cable/source-files-FRITZ.Box_6490_Cable.atom-07.01.tar.gz
./fritzbox/fritzbox-6490-cable/source-files-FRITZ.Box_6490_Cable.atom-07.02.tar.gz
./fritzbox/fritzbox-6590-cable/source-files-FRITZ.Box_6590_Cable-07.00.tar.gz
./fritzbox/fritzbox-6590-cable/source-files-FRITZ.Box_6590_Cable-07.02.tar.gz
./fritzbox/fritzbox-6590-cable/source-files-FRITZ.Box_6590_Cable.atom-07.00.tar.gz
./fritzbox/fritzbox-6590-cable/source-files-FRITZ.Box_6590_Cable.atom-07.02.tar.gz
./fritzbox/fritzbox-6890-lte/source-files-FRITZ.Box_6890_LTE-07.01.tar.gz
./fritzbox/fritzbox-7430/source-files-FRITZ.Box_7430-07.01.tar.gz
./fritzbox/fritzbox-7490/source-files-FRITZ.Box_7490-07.01.tar.gz
./fritzbox/fritzbox-7490/source-files-FRITZ.Box_scrpn_7490-07.01.tar.gz
./fritzbox/fritzbox-7530/source-files-FRITZ.Box_7530-07.02.tar.gz
./fritzbox/fritzbox-7530/source-files-FRITZ.Box_7530-07.03.tar.gz
./fritzbox/fritzbox-7580/source-files-FRITZ.Box_7580-07.00.tar.gz
./fritzbox/fritzbox-7590/source-files-FRITZ.Box_7590-07.00.tar.gz
./fritzbox/fritzbox-7590/source-files-FRITZ.Box_7590-07.01.tar.gz
./fritzwlan/fritzwlan-repeater-1750e/source-files-FRITZ.Box_WLAN_Repeater_1750E-07.01.tar.gz
vidar:~/osp.avm.de $
```

Most devices with a different architecture (e.g. the Broadcom-based 758[12]) have no corresponding open-source package yet. Is there anybody interested in writing the required mail(s) to AVM? :angry: 

The 7530 sources are available (also ARM Cortex A9) ... but do the chipsets provide the same functionalities, especially for the "packet accelerator" topic? I don't know this ... but at least the sources for 7530 (07.03) do not include the BUG_ON lines:

```C
4098 static int __netif_receive_skb(struct sk_buff *skb)
4099 {
4100         int ret;
4101
4102         if (sk_memalloc_socks() && skb_pfmemalloc(skb)) {
4103                 unsigned long pflags = current->flags;
4104
4105                 /*
4106                  * PFMEMALLOC skbs are special, they should
4107                  * - be delivered to SOCK_MEMALLOC sockets only
4108                  * - stay away from userspace
4109                  * - have bounded memory usage
4110                  *
4111                  * Use PF_MEMALLOC as this saves us from propagating the allocation
4112                  * context down to all allocation sites.
4113                  */
4114                 current->flags |= PF_MEMALLOC;
4115                 ret = __netif_receive_skb_core(skb, true);
4116                 tsk_restore_flags(current, pflags, PF_MEMALLOC);
4117         } else
4118                 ret = __netif_receive_skb_core(skb, false);
4119
4120         return ret;
4121 }
4122
4123 static int netif_receive_skb_internal(struct sk_buff *skb)
4124 {
4125         int ret;
4126
4127         net_timestamp_check(netdev_tstamp_prequeue, skb);
4128
4129         if (skb_defer_rx_timestamp(skb))
4130                 return NET_RX_SUCCESS;
4131
4132         rcu_read_lock();
4133
4134 #ifdef CONFIG_RPS
4135         if (static_key_false(&rps_needed)) {
4136                 struct rps_dev_flow voidflow, *rflow = &voidflow;
4137                 int cpu = get_rps_cpu(skb->dev, skb, &rflow);
4138
4139                 if (cpu >= 0) {
4140                         ret = enqueue_to_backlog(skb, cpu, &rflow->last_qtail);
4141                         rcu_read_unlock();
4142                         return ret;
4143                 }
4144         }
4145 #endif
4146         ret = __netif_receive_skb(skb);
4147         rcu_read_unlock();
4148         return ret;
4149 }
4150
4151 /**
4152  *      netif_receive_skb - process receive buffer from network
4153  *      @skb: buffer to process
4154  *
4155  *      netif_receive_skb() is the main receive data processing function.
4156  *      It always succeeds. The buffer may be dropped during processing
4157  *      for congestion control or by the protocol layers.
4158  *
4159  *      This function may only be called from softirq context and interrupts
4160  *      should be enabled.
4161  *
4162  *      Return values (usually ignored):
4163  *      NET_RX_SUCCESS: no congestion
4164  *      NET_RX_DROP: packet was dropped
4165  */
4166 int netif_receive_skb(struct sk_buff *skb)
4167 {
4168         trace_netif_receive_skb_entry(skb);
4169
4170         return netif_receive_skb_internal(skb);
4171 }
4172 EXPORT_SYMBOL(netif_receive_skb);

```

So at least the 7530 is not affected.

BTW: If the FRITZ!Box 6591 gets really released in a couple of days (I think, "weeks" as unit is more realistic thinking), I'm interested in the Puma7 sources and I'll ask AVM for it immediately myself. I'm curious, whether and how AVM uses the virtualization features provided by this chipset.

**Comment by er13** [comment]
Still draft? Or is it ok to merge it? Looks good to me.

**Comment by PeterPawn** [comment]
> Still draft?

Yes ... but if you want to merge the current changes (especially the new symbols I'd think?), it's OK for me, too. That's why I make this one "ready for preview" now.

But please do not be surprised, if I'll open another PR draft right after this one gets merged ... I want to enhance the LKM a little bit. Initially I wanted to use this PR for a new version (of C source) and the currently visible changes were only in addition to further, planned commits. If the branch gets deleted, I have to re-create a new one for further work.

_I have had big parts of "procfs" support already, until I did an accidentally "git reset --hard" in the wrong branch two month ago. Now I have to use my terminal logs to reconstruct these parts or I must reimplement them ... but no matter which option I choose, I want to further expand the LKM._

**Pull request merged**
