### PR TITLE
ncurses: add support for a different install location in file system

### PR DESCRIPTION
**Pull request by PeterPawn**
- move the additional options to the generator script (after this was moved into the package directory)

- maybe I've missed dependencies for automatic rebuilds, after the location settings were changed

### CODE REVIEW

**Comment by kriegaex** [comment]
What has a different location on the file system? Please do not use commit comments requiring me to read the full diff in order to know what you did when I just want to use "git log".

**Comment by er13** [comment]
What is the use-case for this change? Is there any outside of YourFritz context?

Just like in #15 I tend to say "this is a very YourFritz specific change".

**Comment by PeterPawn** [comment]
I would think, that a relocatable ncurses installation provides also further opportunities for Freetz packages.

If you call most of the prior static-linkage changes somewhat "YourFritz specific", I would understand it more.

But I see really use cases for a "moveable" ncurses library, first at all with "plugin-like" images for additional packages in mind and here a fixed path to the 'ncurses' databases in any of the (ncurses) libraries is a big problem.

Freetz may today already create separate files for each externalized package with EXTERNAL_CREATEPAK_DYNAMIC ... further steps to make such a separate file a more "autonomous extension package", should not be too difficult.

You may relocate the libraries themselves without any hassle (as long as LD_LIBRARY_PATH is taken into account by uClibc) and you may simply specify their new location, but you cannot relocate the terminfo database this way (afaik).

Only if these fixed path names are substituted (step by step and the behavior was not changed for the default values), you may get a chance to extend the firmware with additional packages, while/where the symlinks to create in the default directories (in the rootfs) are not known already at build-time.

With relocatable standard components (libraries are much easier to shift as mentioned above) you get at all a chance to create small "self-contained" images, which behave a little bit like packages from a "normal" distribution repository used by "big systems" (but without dependency handling and therefore with the need, to put it all together into a single image).

While most packages may relocatable themselves with appropriate options for their own "autoconf" capabilities, 'ncurses' is an example, where it's impossible (from the view of a package, which wants only to use the 'ncurses' installation). 

If such a package could build its own and proper relocated version(s) of the 'ncurses' libraries, it may include them into its own image - they may be duplicate in some cases, but - and that's another benefit - they're always from the needed version.

Such a package still needs to know at build-time, where this extension image will later be mounted (at least for the 'ncurses' databases)  ... but that's only a small obstacle compared to a fixed path in the read-only file system, where it may be symlinked at build-time to "somewhere" (which may fool other software, if it's missing in reality), but it can't be really added later (something like "on demand") there.

Maybe this could be written much shorter ... I want to bring over, that these changes have an advantage also for other Freetz packages (or at least they could have one).

**Comment by PeterPawn** [comment]
Oops, wrong button ... feel free to re-open or leave it closed - it's your decision.

**Comment by er13** [comment]
Most of the "create a statically linked binary"-options are only useful in non-freetz contexts. YourFritz is just one of these non-freetz contexts. So in this sense, yes, all of them are "YourFritz specific". Btw. even the help text from your commit says "if you don't use the original Freetz image".

I still don't understand the use-case for freetz, you probably misunderstand what exactly external does. It is miles away from providing really dynamic packages. It still requires full blown freetz-mod - because external handling is an integrated, as of now non-separable part of it. As long as this is the case, it doesn't really matter if terminfo/tabset db is relocatable or not.

Freetz is nevertheless (see number of "static linking" options it supports) quite friendly to non-freetz contexts. I could imagine to integrate your change but without making it visible in menuconfig (i.e. with prompt line commented out). Would that be ok for you?

**Comment by PeterPawn** [comment]
Let's discuss another approach, which may help to keep the (make) user interface for Freetz users as simple as possible, while supporting non-freetz extensions more and better.

All of my attempts to re-integrate (usually working and tested) patches into the Freetz tool-chain are intended to avoid duplicated effort on your and my side. I know, that some additions are not obviously useful for users of a full-blown Freetz *image* ... I thought, that new ideas and new approaches nonetheless could be welcome. 

---

Maybe there's a question to answer at the beginning: What is Freetz? What think the maintainers regarding future extensions or enhancements?

Is it an offer for a re-usable tool-chain and already adapted open source packages, which could/should be used (as much as possible) by other - even non-freetz - users or is is more a monolithic project with the final goal to get in each case an flashable image for a FRITZ!Box?

My own older thesis, that it's a project consisting of four main parts, which are (unfortunately) interwoven too much (in my opinion and the current VCS structure is a clear sign of it), should be known.

Some changes (e.g. the 'non-freetz' mode to add only user-defined content to an original image or the - older - options for 'fwmod' to handle single steps of a modification) had let me assume two or three years ago, the first point of view would be an acceptable one, too. And the user may decide freely, whether he takes only parts of the Freetz offer and re-uses them to realize his own ideas (or even dreams) or whether he wants more the "whole Freetz" and uses a 'genuine image', built with this project.

These 'non-freetz' users still may benefit from version bumps and already existing patches for various open source packages ... in my opinion it's a waste of time to fork this project simply and to (independently) incorporate future upstream updates once again (and again and again), if the Freetz project is willing to accept a role as 'source of tool-chain and packages' for FRITZ!Box devices. The OpenWRT project is another example of such a role - but mostly intended for devices from other vendors, while Freetz is specialized to FRITZ!OS-based devices.

---

If your answer is: "Re-use of the Freetz tool-chain and (adapted) package repository for other purposes is very welcome.", a solution to keep the (make) interface still as simple as possible for Freetz users, is a understandable desire.

What do you think of an additional mode (hidden in the experts settings), as a precondition to display all these packages and settings in Kconfig, which are intended to support  only non-freetz usage (or are primarily intended for this purpose)?

To change the whole auto-configuration process in the current Freetz tool-chain is a really big effort ... and I can see the idea behind this intention, but it's unnecessary for most packages. Only those, which incorporate such a fixed path into their own code during configuration, need to be changed. If you start to change the "--prefix" setting for all packages, the (by some Freetz packages used) 'install' target of their own Makefiles will be affected, too. This leads to a different structure in your staging directory and needs further changes ... and so on. Some upstream software is already prepared for cross-compilations, other ones needs to be patched.

If you want the really big thing at the very first beginning, an insuperable mountain of problems is in front of you. 

---

Surely, I know what 'externals' in its current state means and does ... my earlier statement regarding orphaned symlinks from the rootfs directories (all of them pointing to '/mod/external/...') to not yet available/mounted/initialized 'external' packages should show this ... and some software may fail, simply due to an orphaned link to any "externalized" library, which it wants to load via 'libdl' (without further precautions).

But I don't think, it's necessary in each case to create these links already at build-time in the rootfs ... at least not for all times in the future. Even the Freetz process of 'externalization' could use an alternative approach (as an addition), which relies on AVM's plug-in loader. 

If this is not an option, only 'non-freetz' usage would benefit from such changes ... but this could be an acceptable intention, too. But - of course - only if the re-use of the first two or three stages from the Freetz project - tool-chain, package repo, modification process (I mean 'fwmod', not 'mod' and 'mod-cgi', they are the fourth part) - is an acceptable "abuse" of the Freetz project.

---

Seriously ... I do not see such intentions only as "leeching" from the work and outcome of others. Sooner or later will other projects (summarized as 'non-freetz') provide useful additions and ideas, which may be incorporated into Freetz and where even 'genuine Freetz users' may benefit from. I'd think, I have already shown this in the past.

**Pull request closed without merging**
