### PR TITLE
privatekeypassword: update to the new version

### PR DESCRIPTION
**Pull request by PeterPawn**
Second try ... same comment.

---

First at all: I know, that the master repository for Freetz is maintained on the SVN server.

Nevertheless I am creating this pull request, as a first attempt to close the gap between these VCS - beside the "SVN bridge" with "git svn".

In any way it should be possible, to patch the SVN trunk with the 'diff' file from this request.

The distributed management with a full-fledged repo at the system of a contributor makes it easier, to suggest patches.

Adding them to a ticket on the Trac server requires an additional account for this (and therefore additional) system and the Trac server wasn't really reliable in the past.

Even if the server seems to be more stable now, it's time (in my opinion) for a more modern offer to contributors.

Soon I will generate more pull requests, without this explanation ... please keep this text for the other requests in mind.

### CODE REVIEW

**Comment by PeterPawn** [comment]
It looks better now ... I'll repeat this for the other branches.

**Comment by kriegaex** [comment]
What do you mean by "repeat this for the other branches"? Create the same commits again? I hope not. This is not the way Git should be used. You could cherry-pick the commits, but even that makes my toenails curl. What you should do instead is create a feature or bugfix branch based on the oldest branch which intend to port it back to and which is also contained in the other target branches' history and then just merge it into each branch, possibly fixing merge conflicts for the more recent branches in the way.

Actually I would suggest another branch/merge workflow for Freetz (or any other project), not the "we all develop on master" one. But that is another topic to be discussed on the dev mailing list or so.

**Comment by PeterPawn** [comment]
And I thought, my comment was clear ... today I've reorganized my complete Freetz  fork and in this context, I had already created separate branches earlier -> one for each package, to which I want to contribute (a precondition for separate/atomic pull requests) ... where is this workflow different from your "claim" to use "feature branches"?

But I wanted to keep my own commit history for the last 18 months and did not want to throw it away without any distress.

As a result, my first attempt of a pull request without a prior "rebase" contained more than 150 older commits from my fork (some of them found their way into the trunk meanwhile, others were (re-)implemented by @er13) and not only the current and real changes to the 3 files affected. 

I've closed this request immediately myself - you should find it in the history of Freetz's upstream master, if you watch the "whole story" and not only the single entry.

After saving my old history to a new branch 'YourFritz_History' (I've protected this branch later), I did a rebase of the whole fork to the current upstream master, recreated my branches for the affected packages and tried a second pull request for the first "feature branch" ... the head-line "Second try ... same comment." for this pull request should express this without any possibilty of misunderstanding (for readers of the whole story).

Afterwards I've checked the result (and content) of the pull request and because I found now the expected result, I've added the comment, which you've read (and which you misunderstood in my opinion). 

**Surely** I have repeated exactly this procedure for each other branch (aka package, where I want to contribute to) ... and I think, it's the correct workflow.

I do not really understand, where you may see a context (or a reason) for "cherry-picking" from previous commits here - I've created all branches on the base of current upstream master. 

On the upstream origin, there are no other (active) branches than the SVN trunk (used as master on GitHub), which are affected and therefore it's needless, to dig deeper in the history to find a valid start point for my branch(es).

Even my own branch (from my fork) named 'YourFritz', which merges together all other "feature branches", is in my opinion the best solution for additional changes, which are not (and never) intended to become pull requests anytime. 

If I want to make such changes, I'll checkout this branch as the "working tree" ... and the same happens, if I want to run a build from this branch to create the needed binaries for my other projects.

In the end I can't see important differences between my current workflow and your claim - if I really did understand you wrong, you should explain it further.

This was only the first (real) attempt to use GitHub for pull requests on Freetz ... there's no existing "agreement", how to name pull requests or use git (and GitHub) for this project.

I'm glad, if there's any feedback ... but I would be lucky, if there is understandable feedback related to the real problem and - I beg your pardon - I'm missing it here or I'm not able to understand your comment.

**Comment by kriegaex** [comment]
Dear Peter,

of course I have seen the first vs. second try and saw that you fixed the history with dozens of commits. No problem there whatsoever. But even your description was so verbose, there was still a misunderstanding: I thought you talked about release branches (basically the only branches used in the SVN repo and thus common among Freetz devs), but you talked about your private story branches. If you had written "other story branches" or "other feature branches" (I know Freetz does not use user stories), I would have understood. But with the ambiguous comment only somebody with context knowledge about how you work can understand correctly. I really thought you wanted to "do the same", i.e. recreate the same commits, on older release branches.

So please, as I said, take no offense. Feedback is feedback, it was meant to be constructive. And if I talk about a branch model in my mind for Freetz, I was not talking about your private branch model which maybe comes close, I do not know. If it does, I salute you, congrats. There is no need to be so defensive, we just talk here. PRs are meant to be discussed and commented so as to maximise learning for both parties, contributor and maintainer (which I am not anymore, don't forget). But I do know quite a bit about Git and want to contribute to the discussion because I strongly favour migration of Freetz to Git(Hub). So we are on the same page here. I also agree that rules for how to use branches and when to merge from where to where else would be benefitial. But the active devs would have to agree on a model first and then write it down. Even as an inactive developer and maintainer I am willing to make suggestions and comments due to my professional background, if you do not mind.

Thank you for your feedback and for your many contributions to Freetz. :-)

**Comment by PeterPawn** [comment]
You already know, that the current Freetz workflow and a distributed version control system aren't the best team at this time.

If you write the whole thoughts about possible changes of workflows in a place, where they will be really read (and imho a foreign PR isn't the right place), there's nothing to comment anymore from my side.

**Comment by kriegaex** [comment]
> If you write the whole thoughts about possible changes of workflows in a place, where they will be really read (and imho a foreign PR isn't the right place), there's nothing to comment anymore from my side.

I did not write "all possible thoughts" about workflow changes, just the minimal ones necessary in the context of this very PR where it belongs in order to give you a context. Criticism should be constructive, and mine was. I explained why I made my suggestion. As for my whole idea about a better workflow, I explicitly said:

>> Actually I would suggest another branch/merge workflow for Freetz (or any other project), not the "we all develop on master" one. But that is another topic to be discussed on the dev mailing list or so.

I did this so as to avoid going off-topic. I do not appreciate off-topic discussions at all, so please read my comments in the context of this PR. I am sorry that you cannot seem to handle feedback, even if polite and backed with arguments. So I will just answer one last time to your comments in the other PRs and then never again bother you. Actually I was glad that someone started to use Git more actively and wanted to support you, even suggest that you become an active member with commit rights instead of maintaining your own fork. But now I see that it is better that you continue to work on your own as you seem to be unable to collaborate in a team context, being allergic to feedback, criticism or improvement ideas.

**Comment by PeterPawn** [comment]
The test to automatically close it with a SVN commit looks good.

There are meanwhile unneeded files in my source project (after further and not thoroughly enough reviewed changes) and I have to rework it again.

**Pull request closed without merging**
